[theme]

# Primary accent for interactive elements
primaryColor = '#fcfcfc'

# Background color for the main content area
backgroundColor = '#caddfa'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffffff'

# Color used for almost all text
textColor = '#1a0080'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace | Ubuntu) 
# Default: "Ubuntu"
font = "Ubuntu"